//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Analyzer.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Russian() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Network_Analyzer.Localization.Resource_Russian", typeof(Resource_Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string ConfigurationClass_Cancel {
            get {
                return ResourceManager.GetString("ConfigurationClass.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка поле Название не может быть пустым.
        /// </summary>
        internal static string ConfigurationClass_ErrorConfigurationNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConfigurationClass.ErrorConfigurationNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данное название уже существует.
        /// </summary>
        internal static string ConfigurationClass_ErrorNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConfigurationClass.ErrorNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название должно начинаться с заглавной буквы.
        /// </summary>
        internal static string ConfigurationClass_ErrorNameBeginCapitalLetter {
            get {
                return ResourceManager.GetString("ConfigurationClass.ErrorNameBeginCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название должно содержать английские буквы и цифры.
        /// </summary>
        internal static string ConfigurationClass_ErrorOnlyEnglishLettersNumbers {
            get {
                return ResourceManager.GetString("ConfigurationClass.ErrorOnlyEnglishLettersNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка опкод не модет быть пустым.
        /// </summary>
        internal static string ConfigurationClass_ErrorOpcodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConfigurationClass.ErrorOpcodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание конфигурации.
        /// </summary>
        internal static string ConfigurationClass_Geleral {
            get {
                return ResourceManager.GetString("ConfigurationClass.Geleral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string ConfigurationClass_Information {
            get {
                return ResourceManager.GetString("ConfigurationClass.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование конфигурации успешно загружено.
        /// </summary>
        internal static string ConfigurationClass_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigurationClass.LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название конфигурации.
        /// </summary>
        internal static string ConfigurationClass_Name {
            get {
                return ResourceManager.GetString("ConfigurationClass.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опкод.
        /// </summary>
        internal static string ConfigurationClass_Opcode {
            get {
                return ResourceManager.GetString("ConfigurationClass.Opcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string ConfigurationClass_Save {
            get {
                return ResourceManager.GetString("ConfigurationClass.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект конфигурации.
        /// </summary>
        internal static string ConfigurationClass_Text {
            get {
                return ResourceManager.GetString("ConfigurationClass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле является массивом.
        /// </summary>
        internal static string ConfigurationField_Array {
            get {
                return ResourceManager.GetString("ConfigurationField.Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина массива.
        /// </summary>
        internal static string ConfigurationField_ArrayLength {
            get {
                return ResourceManager.GetString("ConfigurationField.ArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string ConfigurationField_Cancel {
            get {
                return ResourceManager.GetString("ConfigurationField.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название или длина.
        /// </summary>
        internal static string ConfigurationField_CommonString {
            get {
                return ResourceManager.GetString("ConfigurationField.CommonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название структуры.
        /// </summary>
        internal static string ConfigurationField_CommonStructure {
            get {
                return ResourceManager.GetString("ConfigurationField.CommonStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание переменной.
        /// </summary>
        internal static string ConfigurationField_Description {
            get {
                return ResourceManager.GetString("ConfigurationField.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка поле Название не может быть пустым.
        /// </summary>
        internal static string ConfigurationField_ErrorFieldNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorFieldNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название уже существует.
        /// </summary>
        internal static string ConfigurationField_ErrorNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название должно начинаться с заглавной буквы.
        /// </summary>
        internal static string ConfigurationField_ErrorNameBeginCapitalLetter {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorNameBeginCapitalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название должно содержать английские буквы и цифры.
        /// </summary>
        internal static string ConfigurationField_ErrorOnlyEnglishLettersNumbers {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorOnlyEnglishLettersNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки в длине массива.
        /// </summary>
        internal static string ConfigurationField_ErrorsArrayLength {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка введена не верная длина.
        /// </summary>
        internal static string ConfigurationField_ErrorsEnteredLengthInvalid {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsEnteredLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка введена не верная структура.
        /// </summary>
        internal static string ConfigurationField_ErrorsEnteredStructureInvalid {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsEnteredStructureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка длина не может быть 0.
        /// </summary>
        internal static string ConfigurationField_ErrorsLengthCanNotBeZero {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsLengthCanNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка длина не может быть пустой.
        /// </summary>
        internal static string ConfigurationField_ErrorsLengthEmpty {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsLengthEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки в позиции.
        /// </summary>
        internal static string ConfigurationField_ErrorsPosition {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка позиция уже используется.
        /// </summary>
        internal static string ConfigurationField_ErrorsPositionAlreadyUse {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsPositionAlreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка структура не может быть пустой.
        /// </summary>
        internal static string ConfigurationField_ErrorsStructureEmpty {
            get {
                return ResourceManager.GetString("ConfigurationField.ErrorsStructureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание поля.
        /// </summary>
        internal static string ConfigurationField_Geleral {
            get {
                return ResourceManager.GetString("ConfigurationField.Geleral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string ConfigurationField_Information {
            get {
                return ResourceManager.GetString("ConfigurationField.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование поля успешно загружено.
        /// </summary>
        internal static string ConfigurationField_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigurationField.LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название переменной.
        /// </summary>
        internal static string ConfigurationField_Name {
            get {
                return ResourceManager.GetString("ConfigurationField.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция.
        /// </summary>
        internal static string ConfigurationField_Position {
            get {
                return ResourceManager.GetString("ConfigurationField.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string ConfigurationField_Save {
            get {
                return ResourceManager.GetString("ConfigurationField.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порядок байтов.
        /// </summary>
        internal static string ConfigurationField_SequenceType {
            get {
                return ResourceManager.GetString("ConfigurationField.SequenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация поля.
        /// </summary>
        internal static string ConfigurationField_Text {
            get {
                return ResourceManager.GetString("ConfigurationField.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип переменной.
        /// </summary>
        internal static string ConfigurationField_Type {
            get {
                return ResourceManager.GetString("ConfigurationField.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        internal static string ConfigurationField_Value {
            get {
                return ResourceManager.GetString("ConfigurationField.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматический скролл.
        /// </summary>
        internal static string Editor_AutoScroll {
            get {
                return ResourceManager.GetString("Editor.AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое обновление.
        /// </summary>
        internal static string Editor_AutoUpdateDataGridView {
            get {
                return ResourceManager.GetString("Editor.AutoUpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связи.
        /// </summary>
        internal static string Editor_Bindings {
            get {
                return ResourceManager.GetString("Editor.Bindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        internal static string Editor_ClassCount {
            get {
                return ResourceManager.GetString("Editor.ClassCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить пакеты.
        /// </summary>
        internal static string Editor_ClearPackets {
            get {
                return ResourceManager.GetString("Editor.ClearPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        internal static string Editor_Configuration {
            get {
                return ResourceManager.GetString("Editor.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить конфигурацию.
        /// </summary>
        internal static string Editor_ConfigurationAdd {
            get {
                return ResourceManager.GetString("Editor.ConfigurationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация успешно создана.
        /// </summary>
        internal static string Editor_ConfigurationCreateSuccessfully {
            get {
                return ResourceManager.GetString("Editor.ConfigurationCreateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить конфигурацию.
        /// </summary>
        internal static string Editor_ConfigurationDelete {
            get {
                return ResourceManager.GetString("Editor.ConfigurationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание конфигурации пакета.
        /// </summary>
        internal static string Editor_ConfigurationDescription {
            get {
                return ResourceManager.GetString("Editor.ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация не может быть пустой.
        /// </summary>
        internal static string Editor_ConfigurationEmpty {
            get {
                return ResourceManager.GetString("Editor.ConfigurationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Editor_ConfigurationFieldAdd {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле конфигурации успешно добавлено.
        /// </summary>
        internal static string Editor_ConfigurationFieldAddedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Editor_ConfigurationFieldDelete {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле конфигурации успешно удалено.
        /// </summary>
        internal static string Editor_ConfigurationFieldDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string Editor_ConfigurationFieldEdit {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Editor_ConfigurationFieldName {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция.
        /// </summary>
        internal static string Editor_ConfigurationFieldPosition {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        internal static string Editor_ConfigurationFieldType {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        internal static string Editor_ConfigurationFieldValue {
            get {
                return ResourceManager.GetString("Editor.ConfigurationFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация успешно загружена.
        /// </summary>
        internal static string Editor_ConfigurationLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.ConfigurationLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название конфигурации пакета.
        /// </summary>
        internal static string Editor_ConfigurationName {
            get {
                return ResourceManager.GetString("Editor.ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурации пакетов.
        /// </summary>
        internal static string Editor_ConfigurationPackets {
            get {
                return ResourceManager.GetString("Editor.ConfigurationPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация успешно сохранена.
        /// </summary>
        internal static string Editor_ConfigurationSuccessfullySaved {
            get {
                return ResourceManager.GetString("Editor.ConfigurationSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать конфигурацию.
        /// </summary>
        internal static string Editor_CreateConfiguration {
            get {
                return ResourceManager.GetString("Editor.CreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина.
        /// </summary>
        internal static string Editor_DataLength {
            get {
                return ResourceManager.GetString("Editor.DataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы данных.
        /// </summary>
        internal static string Editor_DataTypes {
            get {
                return ResourceManager.GetString("Editor.DataTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декриптор.
        /// </summary>
        internal static string Editor_Decryptor {
            get {
                return ResourceManager.GetString("Editor.Decryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декриптор успешно загружен.
        /// </summary>
        internal static string Editor_DecryptorLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.DecryptorLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декриптор успешно выгружен.
        /// </summary>
        internal static string Editor_DecryptorUnloadedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.DecryptorUnloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат загрузки не может быть пустым.
        /// </summary>
        internal static string Editor_DeserializationResultEmpty {
            get {
                return ResourceManager.GetString("Editor.DeserializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ASCII.
        /// </summary>
        internal static string Editor_EncodingAscii {
            get {
                return ResourceManager.GetString("Editor.EncodingAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unicode.
        /// </summary>
        internal static string Editor_EncodingUnicode {
            get {
                return ResourceManager.GetString("Editor.EncodingUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UTF8.
        /// </summary>
        internal static string Editor_EncodingUTF8 {
            get {
                return ResourceManager.GetString("Editor.EncodingUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows-1251.
        /// </summary>
        internal static string Editor_EncodingWindows1251 {
            get {
                return ResourceManager.GetString("Editor.EncodingWindows1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Editor_Error {
            get {
                return ResourceManager.GetString("Editor.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не загрузили декриптор.
        /// </summary>
        internal static string Editor_ErrorLoadingDecryptor {
            get {
                return ResourceManager.GetString("Editor.ErrorLoadingDecryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при загрузке пакета.
        /// </summary>
        internal static string Editor_ErrorLoadingPacket {
            get {
                return ResourceManager.GetString("Editor.ErrorLoadingPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните поле поиска.
        /// </summary>
        internal static string Editor_ErrorNotFillSerchField {
            get {
                return ResourceManager.GetString("Editor.ErrorNotFillSerchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка данное название конфигурации уже используется.
        /// </summary>
        internal static string Editor_ErrorsConfigurationNameAlreadyUse {
            get {
                return ResourceManager.GetString("Editor.ErrorsConfigurationNameAlreadyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип поиска.
        /// </summary>
        internal static string Editor_ErrorSelectSearchType {
            get {
                return ResourceManager.GetString("Editor.ErrorSelectSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при сохранении конфигурации.
        /// </summary>
        internal static string Editor_ErrorsSavingConfiguration {
            get {
                return ResourceManager.GetString("Editor.ErrorsSavingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите расшифровынные пакеты.
        /// </summary>
        internal static string Editor_ErrorsSelectDecryptedPackages {
            get {
                return ResourceManager.GetString("Editor.ErrorsSelectDecryptedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при выборе кодировки.
        /// </summary>
        internal static string Editor_ErrorsSelectEncoding {
            get {
                return ResourceManager.GetString("Editor.ErrorsSelectEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки в начальном индексе.
        /// </summary>
        internal static string Editor_ErrorsStartIndex {
            get {
                return ResourceManager.GetString("Editor.ErrorsStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при обновлении пакетов.
        /// </summary>
        internal static string Editor_ErrorsUpdatePackets {
            get {
                return ResourceManager.GetString("Editor.ErrorsUpdatePackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации.
        /// </summary>
        internal static string Editor_ErrorsValidation {
            get {
                return ResourceManager.GetString("Editor.ErrorsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная информация.
        /// </summary>
        internal static string Editor_GeneralInformation {
            get {
                return ResourceManager.GetString("Editor.GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hex редактор.
        /// </summary>
        internal static string Editor_HexEditor {
            get {
                return ResourceManager.GetString("Editor.HexEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодировка.
        /// </summary>
        internal static string Editor_HexEditorEncoding {
            get {
                return ResourceManager.GetString("Editor.HexEditorEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Editor_Information {
            get {
                return ResourceManager.GetString("Editor.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить конфигурацию.
        /// </summary>
        internal static string Editor_LoadConfiguration {
            get {
                return ResourceManager.GetString("Editor.LoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить декриптор.
        /// </summary>
        internal static string Editor_LoadDecryptor {
            get {
                return ResourceManager.GetString("Editor.LoadDecryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор успешно загружен.
        /// </summary>
        internal static string Editor_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("Editor.LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не расшифровано.
        /// </summary>
        internal static string Editor_NotDecrypted {
            get {
                return ResourceManager.GetString("Editor.NotDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлено.
        /// </summary>
        internal static string Editor_NotInstalled {
            get {
                return ResourceManager.GetString("Editor.NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали файл.
        /// </summary>
        internal static string Editor_NotSelectFile {
            get {
                return ResourceManager.GetString("Editor.NotSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Editor_PacketInformation {
            get {
                return ResourceManager.GetString("Editor.PacketInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Editor_PacketName {
            get {
                return ResourceManager.GetString("Editor.PacketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опкод.
        /// </summary>
        internal static string Editor_PacketOpcode {
            get {
                return ResourceManager.GetString("Editor.PacketOpcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакеты.
        /// </summary>
        internal static string Editor_Packets {
            get {
                return ResourceManager.GetString("Editor.Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип пакета.
        /// </summary>
        internal static string Editor_PacketType {
            get {
                return ResourceManager.GetString("Editor.PacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить конфигурацию.
        /// </summary>
        internal static string Editor_SaveConfiguration {
            get {
                return ResourceManager.GetString("Editor.SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Байты.
        /// </summary>
        internal static string Editor_SearchBytes {
            get {
                return ResourceManager.GetString("Editor.SearchBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        internal static string Editor_SearchClear {
            get {
                return ResourceManager.GetString("Editor.SearchClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Editor_SearchName {
            get {
                return ResourceManager.GetString("Editor.SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опкод.
        /// </summary>
        internal static string Editor_SearchOpcode {
            get {
                return ResourceManager.GetString("Editor.SearchOpcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        internal static string Editor_SearchStart {
            get {
                return ResourceManager.GetString("Editor.SearchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск успешно применен.
        /// </summary>
        internal static string Editor_SearchSuccessfullyApplied {
            get {
                return ResourceManager.GetString("Editor.SearchSuccessfullyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск успешно очищен.
        /// </summary>
        internal static string Editor_SearchSuccessfullyCleared {
            get {
                return ResourceManager.GetString("Editor.SearchSuccessfullyCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все пакеты.
        /// </summary>
        internal static string Editor_SelectAllPackets {
            get {
                return ResourceManager.GetString("Editor.SelectAllPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От клиента к серверу.
        /// </summary>
        internal static string Editor_SelectClientToServer {
            get {
                return ResourceManager.GetString("Editor.SelectClientToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расшифрованные.
        /// </summary>
        internal static string Editor_SelectDecrypted {
            get {
                return ResourceManager.GetString("Editor.SelectDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индекс байта .
        /// </summary>
        internal static string Editor_SelectedIndex {
            get {
                return ResourceManager.GetString("Editor.SelectedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрано байт.
        /// </summary>
        internal static string Editor_SelectedLength {
            get {
                return ResourceManager.GetString("Editor.SelectedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зашифрованные.
        /// </summary>
        internal static string Editor_SelectEncrypted {
            get {
                return ResourceManager.GetString("Editor.SelectEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От сервера к клиенту.
        /// </summary>
        internal static string Editor_SelectServerToClient {
            get {
                return ResourceManager.GetString("Editor.SelectServerToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порядок байтов.
        /// </summary>
        internal static string Editor_SequenceType {
            get {
                return ResourceManager.GetString("Editor.SequenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат сохранения не может быть пустым.
        /// </summary>
        internal static string Editor_SerializationResultEmpty {
            get {
                return ResourceManager.GetString("Editor.SerializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string Editor_StructureEdit {
            get {
                return ResourceManager.GetString("Editor.StructureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Editor_StructureName {
            get {
                return ResourceManager.GetString("Editor.StructureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Структуры.
        /// </summary>
        internal static string Editor_Structures {
            get {
                return ResourceManager.GetString("Editor.Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network Analyzer - Редактор | 2019 © Bo0m21.
        /// </summary>
        internal static string Editor_Text {
            get {
                return ResourceManager.GetString("Editor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузить декриптор.
        /// </summary>
        internal static string Editor_UnloadDecryptor {
            get {
                return ResourceManager.GetString("Editor.UnloadDecryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить пакеты.
        /// </summary>
        internal static string Editor_UpdatePackets {
            get {
                return ResourceManager.GetString("Editor.UpdatePackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего соединений.
        /// </summary>
        internal static string Main_AllConnections {
            get {
                return ResourceManager.GetString("Main.AllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое сохранение.
        /// </summary>
        internal static string Main_AutoSaveConnections {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение пакетов отключено.
        /// </summary>
        internal static string Main_AutoSaveConnectionsDisabled {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnectionsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение пакетов включено.
        /// </summary>
        internal static string Main_AutoSaveConnectionsEnabled {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnectionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое обновление.
        /// </summary>
        internal static string Main_AutoUpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.AutoUpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автообновление пакетов отключено.
        /// </summary>
        internal static string Main_AutoUpdatePackagesDisabled {
            get {
                return ResourceManager.GetString("Main.AutoUpdatePackagesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автообновление пакетов включено.
        /// </summary>
        internal static string Main_AutoUpdatePackagesEnabled {
            get {
                return ResourceManager.GetString("Main.AutoUpdatePackagesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить соединения.
        /// </summary>
        internal static string Main_ClearConnentions {
            get {
                return ResourceManager.GetString("Main.ClearConnentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения.
        /// </summary>
        internal static string Main_Connections {
            get {
                return ResourceManager.GetString("Main.Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес клиента.
        /// </summary>
        internal static string Main_Connections_ClientAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        internal static string Main_Connections_Disconnected {
            get {
                return ResourceManager.GetString("Main.Connections.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string Main_Connections_No {
            get {
                return ResourceManager.GetString("Main.Connections.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено.
        /// </summary>
        internal static string Main_Connections_Received {
            get {
                return ResourceManager.GetString("Main.Connections.Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено.
        /// </summary>
        internal static string Main_Connections_Send {
            get {
                return ResourceManager.GetString("Main.Connections.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес сервера.
        /// </summary>
        internal static string Main_Connections_ServerAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Main_Connections_Yes {
            get {
                return ResourceManager.GetString("Main.Connections.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения не могут быть пустыми.
        /// </summary>
        internal static string Main_ConnectionsEmpty {
            get {
                return ResourceManager.GetString("Main.ConnectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с гридом соединений.
        /// </summary>
        internal static string Main_ConnectionsGridWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsGridWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно очищены и обновлены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyCleanedUpdated {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyCleanedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно загружены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно сохранены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullySaved {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно обновлены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с соединениями.
        /// </summary>
        internal static string Main_ConnectionsWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат загрузки не может быть пустым.
        /// </summary>
        internal static string Main_DeserializationResultEmpty {
            get {
                return ResourceManager.GetString("Main.DeserializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при выборе соединения.
        /// </summary>
        internal static string Main_ErrorsChoosingConnection {
            get {
                return ResourceManager.GetString("Main.ErrorsChoosingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при загрузке соединений.
        /// </summary>
        internal static string Main_ErrorsLoadingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsLoadingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при сохранении соединений.
        /// </summary>
        internal static string Main_ErrorsSavingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsSavingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при запуске слушателя.
        /// </summary>
        internal static string Main_ErrorsStartingListener {
            get {
                return ResourceManager.GetString("Main.ErrorsStartingListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при остановке слушателя.
        /// </summary>
        internal static string Main_ErrorsStoppingListener {
            get {
                return ResourceManager.GetString("Main.ErrorsStoppingListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обновлении соединений.
        /// </summary>
        internal static string Main_ErrorsUpdatingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsUpdatingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Main_Information {
            get {
                return ResourceManager.GetString("Main.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель соединений уже запущен.
        /// </summary>
        internal static string Main_ListenerAlreadyStarted {
            get {
                return ResourceManager.GetString("Main.ListenerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель успешно запущен.
        /// </summary>
        internal static string Main_ListenerSuccessfullyLaunched {
            get {
                return ResourceManager.GetString("Main.ListenerSuccessfullyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель успешно остановлен.
        /// </summary>
        internal static string Main_ListenerSuccessfullyStopped {
            get {
                return ResourceManager.GetString("Main.ListenerSuccessfullyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление слушателем.
        /// </summary>
        internal static string Main_ListenerWork {
            get {
                return ResourceManager.GetString("Main.ListenerWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить соединения.
        /// </summary>
        internal static string Main_LoadConnections {
            get {
                return ResourceManager.GetString("Main.LoadConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа успешно загружена.
        /// </summary>
        internal static string Main_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("Main.LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено соединение для редактирования.
        /// </summary>
        internal static string Main_NoConnectionFoundForEditing {
            get {
                return ResourceManager.GetString("Main.NoConnectionFoundForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали файл.
        /// </summary>
        internal static string Main_NotSelectFile {
            get {
                return ResourceManager.GetString("Main.NotSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить соединения.
        /// </summary>
        internal static string Main_SaveConnections {
            get {
                return ResourceManager.GetString("Main.SaveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат сохранения не может быть пустым.
        /// </summary>
        internal static string Main_SerializationResultEmpty {
            get {
                return ResourceManager.GetString("Main.SerializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Main_Settings {
            get {
                return ResourceManager.GetString("Main.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить слушатель.
        /// </summary>
        internal static string Main_StartListener {
            get {
                return ResourceManager.GetString("Main.StartListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить слушатель.
        /// </summary>
        internal static string Main_StopListener {
            get {
                return ResourceManager.GetString("Main.StopListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network Analyzer - Соединения | 2019 © Bo0m21.
        /// </summary>
        internal static string Main_Text {
            get {
                return ResourceManager.GetString("Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить грид соединений.
        /// </summary>
        internal static string Main_UpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.UpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string Main_Version {
            get {
                return ResourceManager.GetString("Main.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big Endian.
        /// </summary>
        internal static string SequenceTypes_BigEndian {
            get {
                return ResourceManager.GetString("SequenceTypes.BigEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Little Endian.
        /// </summary>
        internal static string SequenceTypes_LittleEndian {
            get {
                return ResourceManager.GetString("SequenceTypes.LittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ип слушателя.
        /// </summary>
        internal static string Settings_AddressListener {
            get {
                return ResourceManager.GetString("Settings.AddressListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при сохранении настроек.
        /// </summary>
        internal static string Settings_ErrorsSavingSettings {
            get {
                return ResourceManager.GetString("Settings.ErrorsSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации адреса.
        /// </summary>
        internal static string Settings_ErrorsValidationAddress {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации папки.
        /// </summary>
        internal static string Settings_ErrorsValidationFolder {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации языка.
        /// </summary>
        internal static string Settings_ErrorsValidationLanguage {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации порта.
        /// </summary>
        internal static string Settings_ErrorsValidationPort {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка сохранения.
        /// </summary>
        internal static string Settings_FolderSaved {
            get {
                return ResourceManager.GetString("Settings.FolderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные настройки.
        /// </summary>
        internal static string Settings_GeneralSettings {
            get {
                return ResourceManager.GetString("Settings.GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Settings_Information {
            get {
                return ResourceManager.GetString("Settings.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки слушателя.
        /// </summary>
        internal static string Settings_ListenerSettings {
            get {
                return ResourceManager.GetString("Settings.ListenerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт слушателя.
        /// </summary>
        internal static string Settings_PortListener {
            get {
                return ResourceManager.GetString("Settings.PortListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык программы.
        /// </summary>
        internal static string Settings_ProgramLanguage {
            get {
                return ResourceManager.GetString("Settings.ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно загружены.
        /// </summary>
        internal static string Settings_SettingsLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Settings.SettingsLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно сохранены.
        /// </summary>
        internal static string Settings_SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("Settings.SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки программы.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Byte.
        /// </summary>
        internal static string Types_Byte {
            get {
                return ResourceManager.GetString("Types.Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double.
        /// </summary>
        internal static string Types_Double {
            get {
                return ResourceManager.GetString("Types.Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Float.
        /// </summary>
        internal static string Types_Float {
            get {
                return ResourceManager.GetString("Types.Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Int.
        /// </summary>
        internal static string Types_Int {
            get {
                return ResourceManager.GetString("Types.Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Long.
        /// </summary>
        internal static string Types_Long {
            get {
                return ResourceManager.GetString("Types.Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sbyte.
        /// </summary>
        internal static string Types_Sbyte {
            get {
                return ResourceManager.GetString("Types.Sbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short.
        /// </summary>
        internal static string Types_Short {
            get {
                return ResourceManager.GetString("Types.Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String.
        /// </summary>
        internal static string Types_String {
            get {
                return ResourceManager.GetString("Types.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structure.
        /// </summary>
        internal static string Types_Structure {
            get {
                return ResourceManager.GetString("Types.Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uint.
        /// </summary>
        internal static string Types_Uint {
            get {
                return ResourceManager.GetString("Types.Uint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ulong.
        /// </summary>
        internal static string Types_Ulong {
            get {
                return ResourceManager.GetString("Types.Ulong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ushort.
        /// </summary>
        internal static string Types_Ushort {
            get {
                return ResourceManager.GetString("Types.Ushort", resourceCulture);
            }
        }
    }
}
