//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Analyzer.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Russian() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Network_Analyzer.Localization.Resource_Russian", typeof(Resource_Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего соединений.
        /// </summary>
        internal static string Main_AllConnections {
            get {
                return ResourceManager.GetString("Main.AllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое сохранение.
        /// </summary>
        internal static string Main_AutoSaveConnections {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение пакетов отключено.
        /// </summary>
        internal static string Main_AutoSaveConnectionsDisabled {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnectionsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение пакетов включено.
        /// </summary>
        internal static string Main_AutoSaveConnectionsEnabled {
            get {
                return ResourceManager.GetString("Main.AutoSaveConnectionsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое обновление.
        /// </summary>
        internal static string Main_AutoUpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.AutoUpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автообновление пакетов отключено.
        /// </summary>
        internal static string Main_AutoUpdatePackagesDisabled {
            get {
                return ResourceManager.GetString("Main.AutoUpdatePackagesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автообновление пакетов включено.
        /// </summary>
        internal static string Main_AutoUpdatePackagesEnabled {
            get {
                return ResourceManager.GetString("Main.AutoUpdatePackagesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить соединения.
        /// </summary>
        internal static string Main_ClearConnentions {
            get {
                return ResourceManager.GetString("Main.ClearConnentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения.
        /// </summary>
        internal static string Main_Connections {
            get {
                return ResourceManager.GetString("Main.Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес клиента.
        /// </summary>
        internal static string Main_Connections_ClientAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        internal static string Main_Connections_Disconnected {
            get {
                return ResourceManager.GetString("Main.Connections.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string Main_Connections_No {
            get {
                return ResourceManager.GetString("Main.Connections.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено.
        /// </summary>
        internal static string Main_Connections_Received {
            get {
                return ResourceManager.GetString("Main.Connections.Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено.
        /// </summary>
        internal static string Main_Connections_Send {
            get {
                return ResourceManager.GetString("Main.Connections.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес сервера.
        /// </summary>
        internal static string Main_Connections_ServerAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Main_Connections_Yes {
            get {
                return ResourceManager.GetString("Main.Connections.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения не могут быть пустыми.
        /// </summary>
        internal static string Main_ConnectionsEmpty {
            get {
                return ResourceManager.GetString("Main.ConnectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с гридом соединений.
        /// </summary>
        internal static string Main_ConnectionsGridWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsGridWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно очищены и обновлены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyCleanedUpdated {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyCleanedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно загружены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно сохранены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullySaved {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения успешно обновлены.
        /// </summary>
        internal static string Main_ConnectionsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Main.ConnectionsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с соединениями.
        /// </summary>
        internal static string Main_ConnectionsWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат загрузки не может быть пустым.
        /// </summary>
        internal static string Main_DeserializationResultEmpty {
            get {
                return ResourceManager.GetString("Main.DeserializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при выборе соединения.
        /// </summary>
        internal static string Main_ErrorsChoosingConnection {
            get {
                return ResourceManager.GetString("Main.ErrorsChoosingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при загрузке соединений.
        /// </summary>
        internal static string Main_ErrorsLoadingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsLoadingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при сохранении соединений.
        /// </summary>
        internal static string Main_ErrorsSavingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsSavingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при запуске слушателя.
        /// </summary>
        internal static string Main_ErrorsStartingListener {
            get {
                return ResourceManager.GetString("Main.ErrorsStartingListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при остановке слушателя.
        /// </summary>
        internal static string Main_ErrorsStoppingListener {
            get {
                return ResourceManager.GetString("Main.ErrorsStoppingListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обновлении соединений.
        /// </summary>
        internal static string Main_ErrorsUpdatingConnections {
            get {
                return ResourceManager.GetString("Main.ErrorsUpdatingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Main_Information {
            get {
                return ResourceManager.GetString("Main.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель соединений уже запущен.
        /// </summary>
        internal static string Main_ListenerAlreadyStarted {
            get {
                return ResourceManager.GetString("Main.ListenerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель успешно запущен.
        /// </summary>
        internal static string Main_ListenerSuccessfullyLaunched {
            get {
                return ResourceManager.GetString("Main.ListenerSuccessfullyLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель успешно остановлен.
        /// </summary>
        internal static string Main_ListenerSuccessfullyStopped {
            get {
                return ResourceManager.GetString("Main.ListenerSuccessfullyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление слушателем.
        /// </summary>
        internal static string Main_ListenerWork {
            get {
                return ResourceManager.GetString("Main.ListenerWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить соединения.
        /// </summary>
        internal static string Main_LoadConnections {
            get {
                return ResourceManager.GetString("Main.LoadConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа успешно загружена.
        /// </summary>
        internal static string Main_LoadedSuccessfully {
            get {
                return ResourceManager.GetString("Main.LoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено соединение для редактирования.
        /// </summary>
        internal static string Main_NoConnectionFoundForEditing {
            get {
                return ResourceManager.GetString("Main.NoConnectionFoundForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали файл.
        /// </summary>
        internal static string Main_NotSelectFile {
            get {
                return ResourceManager.GetString("Main.NotSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить соединения.
        /// </summary>
        internal static string Main_SaveConnections {
            get {
                return ResourceManager.GetString("Main.SaveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат сохранения не может быть пустым.
        /// </summary>
        internal static string Main_SerializationResultEmpty {
            get {
                return ResourceManager.GetString("Main.SerializationResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Main_Settings {
            get {
                return ResourceManager.GetString("Main.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить слушатель.
        /// </summary>
        internal static string Main_StartListener {
            get {
                return ResourceManager.GetString("Main.StartListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить слушатель.
        /// </summary>
        internal static string Main_StopListener {
            get {
                return ResourceManager.GetString("Main.StopListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network Analyzer - Соединения | 2019 © Bo0m21.
        /// </summary>
        internal static string Main_Text {
            get {
                return ResourceManager.GetString("Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить грид соединений.
        /// </summary>
        internal static string Main_UpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.UpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string Main_Version {
            get {
                return ResourceManager.GetString("Main.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ип слушателя.
        /// </summary>
        internal static string Settings_AddressListener {
            get {
                return ResourceManager.GetString("Settings.AddressListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при сохранении настроек.
        /// </summary>
        internal static string Settings_ErrorsSavingSettings {
            get {
                return ResourceManager.GetString("Settings.ErrorsSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации адреса.
        /// </summary>
        internal static string Settings_ErrorsValidationAddress {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации папки.
        /// </summary>
        internal static string Settings_ErrorsValidationFolder {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации языка.
        /// </summary>
        internal static string Settings_ErrorsValidationLanguage {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибки при валидации порта.
        /// </summary>
        internal static string Settings_ErrorsValidationPort {
            get {
                return ResourceManager.GetString("Settings.ErrorsValidationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка сохранения.
        /// </summary>
        internal static string Settings_FolderSaved {
            get {
                return ResourceManager.GetString("Settings.FolderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные настройки.
        /// </summary>
        internal static string Settings_GeneralSettings {
            get {
                return ResourceManager.GetString("Settings.GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Settings_Information {
            get {
                return ResourceManager.GetString("Settings.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки слушателя.
        /// </summary>
        internal static string Settings_ListenerSettings {
            get {
                return ResourceManager.GetString("Settings.ListenerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт слушателя.
        /// </summary>
        internal static string Settings_PortListener {
            get {
                return ResourceManager.GetString("Settings.PortListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык программы.
        /// </summary>
        internal static string Settings_ProgramLanguage {
            get {
                return ResourceManager.GetString("Settings.ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно загружены.
        /// </summary>
        internal static string Settings_SettingsLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Settings.SettingsLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки успешно сохранены.
        /// </summary>
        internal static string Settings_SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("Settings.SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки программы.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings.Text", resourceCulture);
            }
        }
    }
}
