//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Analyzer.Localization.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Network_Analyzer.Localization.Languages.Resource_ru", typeof(Resource_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего соединений:.
        /// </summary>
        internal static string Main_AllConnections {
            get {
                return ResourceManager.GetString("Main.AllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое обновление.
        /// </summary>
        internal static string Main_AutoUpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.AutoUpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить соединения.
        /// </summary>
        internal static string Main_ClearConnentions {
            get {
                return ResourceManager.GetString("Main.ClearConnentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить грид.
        /// </summary>
        internal static string Main_ClearDataGridView {
            get {
                return ResourceManager.GetString("Main.ClearDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения.
        /// </summary>
        internal static string Main_Connections {
            get {
                return ResourceManager.GetString("Main.Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес клиента.
        /// </summary>
        internal static string Main_Connections_ClientAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        internal static string Main_Connections_Disconnected {
            get {
                return ResourceManager.GetString("Main.Connections.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string Main_Connections_No {
            get {
                return ResourceManager.GetString("Main.Connections.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено.
        /// </summary>
        internal static string Main_Connections_Received {
            get {
                return ResourceManager.GetString("Main.Connections.Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено.
        /// </summary>
        internal static string Main_Connections_Send {
            get {
                return ResourceManager.GetString("Main.Connections.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес сервера.
        /// </summary>
        internal static string Main_Connections_ServerAddress {
            get {
                return ResourceManager.GetString("Main.Connections.ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Main_Connections_Yes {
            get {
                return ResourceManager.GetString("Main.Connections.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительно.
        /// </summary>
        internal static string Main_ConnectionsGridWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsGridWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа с соединениями.
        /// </summary>
        internal static string Main_ConnectionsWork {
            get {
                return ResourceManager.GetString("Main.ConnectionsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление.
        /// </summary>
        internal static string Main_Control {
            get {
                return ResourceManager.GetString("Main.Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Main_Information {
            get {
                return ResourceManager.GetString("Main.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить соединения.
        /// </summary>
        internal static string Main_LoadConnections {
            get {
                return ResourceManager.GetString("Main.LoadConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть в трей.
        /// </summary>
        internal static string Main_RollToTray {
            get {
                return ResourceManager.GetString("Main.RollToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить соединения.
        /// </summary>
        internal static string Main_SaveConnections {
            get {
                return ResourceManager.GetString("Main.SaveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить.
        /// </summary>
        internal static string Main_StartListener {
            get {
                return ResourceManager.GetString("Main.StartListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить.
        /// </summary>
        internal static string Main_StopListener {
            get {
                return ResourceManager.GetString("Main.StopListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network Analyzer - Соединения | 2019 © Bo0m21.
        /// </summary>
        internal static string Main_Text {
            get {
                return ResourceManager.GetString("Main.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить грид.
        /// </summary>
        internal static string Main_UpdateDataGridView {
            get {
                return ResourceManager.GetString("Main.UpdateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        internal static string Main_Version {
            get {
                return ResourceManager.GetString("Main.Version", resourceCulture);
            }
        }
    }
}
